CREATE TABLE [dbo].[TBAposta]
(
	[IdAposta] INT NOT NULL IDENTITY(1,1), 
    [ValorAposta] DECIMAL(18, 2) NOT NULL, 
    [ValorTotal] DECIMAL(18, 2) NOT NULL, 
    [ConcursoId] INT NOT NULL, 
    [BolaoId] INT NULL,
	CONSTRAINT [FK_TBAposta_ToTBConcurso] FOREIGN KEY ([ConcursoId]) REFERENCES [TBConcurso]([IdConcurso]),
	CONSTRAINT [FK_TBAposta_ToTBBolao] FOREIGN KEY ([BolaoId]) REFERENCES [TBBolao]([IdBolao]),
	CONSTRAINT [PK_Aposta] PRIMARY KEY CLUSTERED

(
	[IdAposta] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
