CREATE TABLE [dbo].[TBBolao]
(
	[IdBolao] INT NOT NULL IDENTITY(1,1), 
    [NumeoApostas] INT NOT NULL, 
    [ValorTotal] DECIMAL(18, 2) NULL,
	CONSTRAINT [PK_Bolao] PRIMARY KEY CLUSTERED

(
	[IdBolao] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

