CREATE TABLE [dbo].[TBConcurso]
(
	[IdConcurso] INT NOT NULL IDENTITY(1,1), 
    [Numero] INT NOT NULL,
	CONSTRAINT [PK_Concurso] PRIMARY KEY CLUSTERED

(
	[IdConcurso] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
