CREATE TABLE [dbo].[TBDezena]
(
	[IdDezena] INT NOT NULL IDENTITY(1,1), 
    [Dezena] INT NOT NULL, 
    [ApostaId] INT NULL, 
    [ConcursoId] INT NULL,
	CONSTRAINT [FK_TBDezena_ToTBAposta] FOREIGN KEY ([ApostaId]) REFERENCES [TBAposta]([IdAposta]),
	CONSTRAINT [FK_TB_ToTBConcurso] FOREIGN KEY ([ConcursoId]) REFERENCES [TBConcurso]([IdConcurso]),
	CONSTRAINT [PK_Dezena] PRIMARY KEY CLUSTERED

(
	[IdDezena] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
